parameters:
    rdv_migration.db_id_name_generator.class:            RDV\Bundle\MigrationBundle\Tools\DbIdentifierNameGenerator
    rdv_migration.data_fixtures.loader.class:            RDV\Bundle\MigrationBundle\Migration\Loader\DataFixturesLoader
    rdv_migration.data_fixtures.executor.class:          Doctrine\Common\DataFixtures\Executor\ORMExecutor
    rdv_migration.migrations.loader.class:               RDV\Bundle\MigrationBundle\Migration\Loader\MigrationsLoader
    rdv_migration.migrations.query_executor.class:       RDV\Bundle\MigrationBundle\Migration\MigrationQueryExecutor
    rdv_migration.migrations.executor.class:             RDV\Bundle\MigrationBundle\Migration\MigrationExecutorWithNameGenerator
    rdv_migration.migration.pre_up.listener.class:       RDV\Bundle\MigrationBundle\EventListener\PreUpMigrationListener
    rdv_migration.migrations.extension_manager.class:    RDV\Bundle\MigrationBundle\Migration\MigrationExtensionManager
    rdv_migration.migration.extension.rename.class:      RDV\Bundle\MigrationBundle\Migration\Extension\RenameExtension
    rdv_migration.tools.schema_dumper.class:             RDV\Bundle\MigrationBundle\Tools\SchemaDumper
    rdv_migration.twig.schema_dumper.class:              RDV\Bundle\MigrationBundle\Twig\SchemaDumperExtension
    rdv_migration.migration.extension.data_strore.class: RDV\Bundle\MigrationBundle\Migration\Extension\DataStorageExtension
services:
    rdv_migration.db_id_name_generator:
        class: %rdv_migration.db_id_name_generator.class%

    rdv_migration.data_fixtures.loader:
        class: %rdv_migration.data_fixtures.loader.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@service_container"

    rdv_migration.data_fixtures.executor:
        class: %rdv_migration.data_fixtures.executor.class%
        arguments:
            - "@doctrine.orm.entity_manager"

    rdv_migration.migrations.loader:
        class: %rdv_migration.migrations.loader.class%
        arguments:
            - "@kernel"
            - "@doctrine.dbal.default_connection"
            - "@service_container"
            - "@event_dispatcher"

    rdv_migration.migrations.query_executor:
        class: %rdv_migration.migrations.query_executor.class%
        arguments:
            - "@doctrine.dbal.default_connection"

    rdv_migration.migrations.executor:
        class: %rdv_migration.migrations.executor.class%
        arguments:
            - "@rdv_migration.migrations.query_executor"
        calls:
            - [setExtensionManager, ["@rdv_migration.migrations.extension_manager"]]
            - [setNameGenerator, ["@rdv_migration.db_id_name_generator"]]

    rdv_migration.migration.pre_up.listener:
        class: %rdv_migration.migration.pre_up.listener.class%
        tags:
            - { name: kernel.event_listener, event: rdv_migration.pre_up, method: onPreUp }

    rdv_migration.migrations.extension_manager:
        class: %rdv_migration.migrations.extension_manager.class%

    rdv_migration.migration.extension.rename:
        class: %rdv_migration.migration.extension.rename.class%
        tags:
            - { name: rdv_migration.extension, extension_name: rename }

    rdv_migration.migration.extension.data_strore:
        class: %rdv_migration.migration.extension.data_strore.class%
        tags:
            - { name: rdv_migration.extension, extension_name: data_store }

    rdv_migration.tools.schema_dumper:
        class: %rdv_migration.tools.schema_dumper.class%
        arguments:
            - "@twig"
        lazy: true

    rdv_migration.twig.schema_dumper:
        class: %rdv_migration.twig.schema_dumper.class%
        arguments:
            - "@doctrine"
        tags:
            - { name: twig.extension }

    rdv_migration.listener.console_command_listener:
        class: RDV\Bundle\MigrationBundle\EventListener\ConsoleCommandListener
        tags:
            - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }
