language: php

sudo: false

cache:
    directory:
        - $HOME/.composer/cache

php:
    - 5.5
    - 5.6
    - 7
    - hhvm

install: composer update

before_script:
    - composer install --dev --no-interaction

script:
    - phpunit -v
